# Generated by Django 4.0.1 on 2022-06-22 11:32

from django.db import migrations, models
import django.db.models.deletion
import host.services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
                ('countrycode', models.CharField(max_length=5)),
                ('phone', models.BigIntegerField()),
                ('place', models.CharField(max_length=40)),
                ('property_type', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to=host.services.change_path)),
            ],
            options={
                'db_table': 'property',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('room_name', models.CharField(max_length=20)),
                ('adult', models.IntegerField()),
                ('child', models.IntegerField()),
                ('price', models.FloatField()),
                ('beds', models.IntegerField()),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.property')),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='property_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_image', models.ImageField(upload_to=host.services.change_path)),
                ('type', models.CharField(default='', max_length=20)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.property')),
            ],
            options={
                'db_table': 'property_images',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.CharField(max_length=12)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.property')),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
