# Generated by Django 4.0.1 on 2022-06-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
