# Generated by Django 4.0.1 on 2022-06-24 11:15

from django.db import migrations, models
import host.services


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_rooms_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_images',
            name='property_image',
            field=models.ImageField(upload_to=host.services.hotel_path),
        ),
    ]
