# Generated by Django 4.0.1 on 2022-06-30 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_alter_property_images_property_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('rules', models.TextField(default='')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.property')),
            ],
            options={
                'db_table': 'about_property',
            },
        ),
    ]
